CREATE TABLE ADDRESSES (
    ADDRESS_ID   NUMBER PRIMARY KEY,
    USER_ID      NUMBER NOT NULL,
    LATITUDE     VARCHAR2(50 BYTE) NOT NULL,
    LONGITUDE    VARCHAR2(50 BYTE) NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ADDRESS_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
);

CREATE SEQUENCE ADDRESSES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER ADDRESSES_TRG
BEFORE INSERT ON ADDRESSES
FOR EACH ROW
BEGIN
    IF :NEW.ADDRESS_ID IS NULL THEN
        SELECT ADDRESSES_SEQ.NEXTVAL
        INTO :NEW.ADDRESS_ID
        FROM DUAL;
    END IF;
END;
/
