CREATE TABLE EMPLOYEE_VERIFICATION (
    VERIFICATION_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'Pending' CHECK (STATUS IN ('Pending', 'Approved', 'Rejected')),
    DOCUMENT_LINK VARCHAR2(500),
    ROLE VARCHAR2(50),
    CONSTRAINT FK_EMP_VER_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE EMPLOYEE_VERIFICATION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER EMPLOYEE_VERIFICATION_TRG
BEFORE INSERT ON EMPLOYEE_VERIFICATION
FOR EACH ROW
BEGIN
  IF :NEW.VERIFICATION_ID IS NULL THEN
    SELECT EMPLOYEE_VERIFICATION_SEQ.NEXTVAL INTO :NEW.VERIFICATION_ID FROM DUAL;
  END IF;

  :NEW.UPDATED_AT := SYSDATE;
END;
/
