CREATE TABLE OTP_VERIFICATION (
    OTP_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    EMAIL VARCHAR2(100) NOT NULL,
    OTP_CODE VARCHAR2(6) NOT NULL,
    EXPIRES_AT DATE DEFAULT (SYSDATE + INTERVAL '5' MINUTE) NOT NULL,
    VERIFIED CHAR(1) DEFAULT 'N' CHECK (VERIFIED IN ('Y', 'N')),
    CONSTRAINT FK_OTP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE OTP_VERIFICATION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER OTP_VERIFICATION_TRG
BEFORE INSERT ON OTP_VERIFICATION
FOR EACH ROW
BEGIN
  IF :NEW.OTP_ID IS NULL THEN
    SELECT OTP_VERIFICATION_SEQ.NEXTVAL INTO :NEW.OTP_ID FROM DUAL;
  END IF;
END;
/

ALTER TABLE SMS_USER.OTP_VERIFICATION MODIFY (USER_ID NULL);
SELECT NULLABLE
FROM USER_TAB_COLS
WHERE TABLE_NAME = 'OTP_VERIFICATION' AND COLUMN_NAME = 'USER_ID';
-- Expect: 'Y'